name: nntiproject
channels:
  - pytorch-nightly
  - huggingface
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - pytorch 
  - torchvision 
  - torchaudio 
  - pytorch-cuda=11.8
  - matplotlib
  - pandas
  - numpy
  - notebook
  - ipywidgets
  - jupyter
  - transformers
  - sentencepiece
  - protobuf
  - huggingface_hub
  - diffusers
  - h5py
  - scikit-learn
  - opentsne